ТЗ 13. Add User and Item
SergeiBrin/java-shareit pull request #1
Opened 2023-04-22 11:16 UTC by SergeiBrin

Добавил логику добавления, изменения, удаления User и item, а также поиска Item по ключевому слову.

2023-04-23 07:52 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +
убери лишние пробелы

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/exception/ItemNotFoundException.java
> +public class ItemNotFoundException extends RuntimeException {
может вынесем пакет exception на уровень с item и user, и экспшены сделаем более общими, не ItemNotFoundException, а NotFoundException

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    && (item.getName().toLowerCase().contains(searchText)
разбей тут на 2 фильтра:
1й - `.filter(item ->
                     item.getAvailable().equals(true)`
2й - `(item.getName().toLowerCase().contains(searchText)|| item.getDescription().toLowerCase().contains(searchText)))`

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/validator/ItemValidator.java
> +    public void checkIfItemExistsById(Long itemId) {
этот класс излишний, просто где ты его используешь делай так:
`Item item repository.getItemById(itemId);
if ( item == null) throw new Exception;
return item;`

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/exception/DuplicateEmailException.java
> +public class DuplicateEmailException extends RuntimeException {
смотри коммент в ItemNotFoundException

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/exception/IncorrectEmailException.java
> +public class IncorrectEmailException extends RuntimeException {
смотри коммент в ItemNotFoundException

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/exception/UserNotFoundException.java
> +public class UserNotFoundException extends RuntimeException {
смотри коммент в ItemNotFoundException

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkEmailForEmpty(User user) {
это можно убрать и добавить в UserDto @NotNUll над email

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +        boolean isNotFound = repository.getUserById(userId) == null;
смотри коммент в ItemValidator

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkEmailUniquenessForPost(User user) {
смотри коммент в ItemValidator

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkEmailUniquenessForPatch(Long userId, User user)  {
смотри коммент в ItemValidator

2023-04-23 07:52 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkConnectionOfUserWithItem(Long userId, Long itemId) {
смотри коммент в ItemValidator

2023-04-23 18:58 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +
+
Убрал :)

2023-04-23 18:59 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/item/exception/ItemNotFoundException.java
> +public class ItemNotFoundException extends RuntimeException {
✅ 
Вынес на уровень с item и user

2023-04-23 18:59 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    && (item.getName().toLowerCase().contains(searchText)
✅ 
Сделано

2023-04-23 18:59 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/item/validator/ItemValidator.java
> +    public void checkIfItemExistsById(Long itemId) {
✅ 
Убрал, перенес нужные проверки в service

2023-04-23 19:00 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/exception/DuplicateEmailException.java
> +public class DuplicateEmailException extends RuntimeException {
🔴 
Так сделать не получается, потому что для createUser() и updateUser() тесты просят разные коды ошибок по неправильному email. Для createUser() - 400, для updateUser() - 409. Проблема в том, что в updateUser() есть patch только по имени, поэтому @Valid User user - не пропустит User с аннотацией @NotNull, который бы проигодился для createUser(), чтобы поймать ошибку 400 и в итоге оставить только DuplicateEmailException(). Вот... :(

2023-04-23 19:00 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/exception/IncorrectEmailException.java
> +public class IncorrectEmailException extends RuntimeException {
🔴 
Так сделать не получается, потому что для createUser() и updateUser() тесты просят разные коды ошибок по неправильному email. Для createUser() - 400, для updateUser() - 409. Проблема в том, что в updateUser() есть patch только по имени, поэтому @Valid User user - не пропустит User с аннотацией @NotNull, который бы проигодился для createUser(), чтобы поймать ошибку 400 и в итоге оставить только DuplicateEmailException(). Вот... :( :(

2023-04-23 19:00 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/exception/UserNotFoundException.java
> +public class UserNotFoundException extends RuntimeException {
✅ 
Сделал только NotFoundExceepption

2023-04-23 19:00 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkEmailForEmpty(User user) {
🔴 
Так сделать не получается, потому что в тестах есть Patch для имени. Он передает только имя - без email.  Следовательно (@Valid @RequestBody User user) такое не пропускает. Как быть?

2023-04-23 19:01 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +        boolean isNotFound = repository.getUserById(userId) == null;
✅ 
Убрал. Перенес логику в Service.

2023-04-23 19:01 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkEmailUniquenessForPost(User user) {
✅ 
Убрал. Перенес логику в Service.

2023-04-23 19:01 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkEmailUniquenessForPatch(Long userId, User user)  {
✅ 
Убрал. Перенес логику в Service.

2023-04-23 19:01 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkConnectionOfUserWithItem(Long userId, Long itemId) {
✅ 
Убрал. Перенес логику в Service.

2023-04-23 19:18 UTC, SergeiBrin commented
Привет Эркин 😄. Как дела?

Я опять в поезде))). Тяжело конечно программировать, когда интернет появляется раз в вечность на пару минут. Но я постарался сделать и так 😆. Надеюсь, что тебе понравится)))

К сожалению, я не устранил два замечания, но в комментах написал почему все так. Зато, благодаря тебе, я сделал хороший рефакторинг кода. Зацени)))

2023-04-24 05:09 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/exception/DuplicateEmailException.java
> +public class DuplicateEmailException extends RuntimeException {
ok

2023-04-24 05:24 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/exception/IncorrectEmailException.java
> +public class IncorrectEmailException extends RuntimeException {
ok

2023-04-24 05:24 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/validator/UserValidator.java
> +    public void checkEmailForEmpty(User user) {
ok, оставь как есть

2023-04-24 05:25 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-04-24 20:47 UTC, merged