sprint 14
SergeiBrin/java-shareit pull request #2
Opened 2023-05-27 04:01 UTC by SergeiBrin

Привет Эркин. Как дела? Как погода в Кыргызстане? 😃 

Работу по 14 ТЗ сделал. Постарался хорошо. Уверен, что ты оценишь :)

Жду обратной связи 😎

2023-05-27 10:57 UTC, ErkinKasymaliev requested changes
привет!
Погода то жаркая, то прохладная)
Оставил комменты

2023-05-27 10:57 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
это аннотация тут не нужна

2023-05-27 10:57 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@RequiredArgsConstructor
это аннотация тоже не нужна

2023-05-27 10:57 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @JoinColumn(name = "user_id")
мой совет: называть поля одинаково что в таблице, что в java классе. А то бывает, что путаешься потом

2023-05-27 10:57 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +@Builder
хмм, не думаю что тут эти аннотации нужны

2023-05-27 10:57 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
>  public class ItemMapper {
тоже не думаю что нужна тут эта аннотация

2023-05-27 10:57 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/model/User.java
>      private final Set<Long> items = new HashSet<>();
почему не Set<Item>?

2023-05-27 10:57 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +//    // + Ищет дубликат email по всем объектам User.
задокументированный код не оставляй, лучше удалить

2023-05-28 12:34 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
✅

2023-05-28 12:35 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +@Builder
✅

2023-05-28 12:36 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
>  public class ItemMapper {
✅

2023-05-28 12:40 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +//    // + Ищет дубликат email по всем объектам User.
✅

2023-05-28 13:07 UTC, SergeiTakt commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@RequiredArgsConstructor
✅ 
Получилось убрать только @ToString и @RequiredArgsConstructor. @Getter убрать не удалось, потому что он используется в BookingMapper, а @Setter - в BookingServiceImpl.

Есть еще кое что: вместо @RequiredArgsConstructor пришлось добавить @NoArgsConstructor, потому что @Builder без этого не хочет работать...

В других классах тоже почистил аннотации.

2023-05-28 15:25 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @JoinColumn(name = "user_id")
✅ 
Некоторые назания переименовал. Некоторые не смог, потому что некоторые слова, как я понимаю, заняты SQL - например «user» и «end». Поэтому я оставил user_id для таблицы users и items: start_time, end_time - для таблицы bookings.

2023-05-28 15:27 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/user/model/User.java
>      private final Set<Long> items = new HashSet<>();
❓ 
Тут вроде Set?
```java
private final Set<Long> items = new HashSet<>();```

2023-05-28 15:41 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/model/User.java
>      private final Set<Long> items = new HashSet<>();
ой, сорян)
почему не Set<Item>?

2023-05-28 15:42 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@RequiredArgsConstructor
я имел виду только @RequiredArgsConstructor

2023-05-29 03:54 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/model/User.java
>      private final Set<Long> items = new HashSet<>();
привет, тут какая та фигня)
`private final Set<Item> items = new HashSet<>();` - вот так долджно быть, почему то не просто Set вставлялось.

2023-05-29 03:55 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
Коммент поправь и можешь мержить

2023-06-05 20:56 UTC, merged