ТЗ 15
SergeiBrin/java-shareit pull request #3
Opened 2023-06-23 02:25 UTC by SergeiBrin

2023-06-23 04:17 UTC, SergeiBrin commented
Господи, я сделал это)))). Привет, Эркин 😃 
Такой жестокий спринт оказался, воооообщеееее... Я почти 2 недели писал эти, блин, тесты - и затратил оооооочень много сил, ух. 

Прости за много коммитов в конце. Я просто побеждал тесты на Гитхаб, поэтому последние 7 коммитов пушил по одному. Пушил и побеждал :)

По приложению, тесты @DataJpaTest написал только для методов с @Query - так предложили сделать в ТЗ. В остальном покрыл приложение тестами очень хорошо. Старался очень. 

Время 9 утра, лягу посплю)))). Очень надеюсь, что правок будет немного, чтобы сердечко не кололо)))).

Жду оценку моим каракулям. До скорых встреч 😎

2023-06-23 05:24 UTC, ErkinKasymaliev requested changes
привет!
Все круто!
Оставил комменты, но они косметические

2023-06-23 05:24 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                "метод searchAvailableItems(), text={}, from={}, size={} ", text, from, size);
в логах from={}, size={} указывать не надо, все равно не информативно

2023-06-23 05:24 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                "Метод getItemsByUser(), userId={}, itemsByUser={}, from={}, size={} ", userId, dbItems, from, size);
то же самое: from={}, size={} не нужен

2023-06-23 05:24 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/mapper/BookingMapperTest.java
> +        assertThat(buildBooking.getStart(), equalTo(reqBookingDto.getStart()));
лучше проще так assertEquals(buildBooking.getStart(), reqBookingDto.getStart()), поправьте везде пожалуйста

2023-06-24 18:53 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                "метод searchAvailableItems(), text={}, from={}, size={} ", text, from, size);
✅

2023-06-24 18:53 UTC, SergeiBrin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                "Метод getItemsByUser(), userId={}, itemsByUser={}, from={}, size={} ", userId, dbItems, from, size);
✅

2023-06-24 19:47 UTC, SergeiBrin commented on src/test/java/ru/practicum/shareit/booking/mapper/BookingMapperTest.java
> +        assertThat(buildBooking.getStart(), equalTo(reqBookingDto.getStart()));
✅ Нашел все сравнение времени cj временем и изменил его на assertEquals. Cравнения на NotNull -assertThat(dbBookingDto.getStart(), is(notNullValue())) изменять не стал. 

Норм?

2023-06-24 19:57 UTC, SergeiBrin commented
Привет, Эркин. Не сразу смог взяться за работу, потому что в стране творится какой-то треш 🤯. 
Я весь день не мог собраться с мыслями и тупо мониторил новости.  К вечеру я все же собрался и устранил твои замечания. Вот.

2023-06-25 14:21 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/mapper/BookingMapperTest.java
> +        assertThat(buildBooking.getStart(), equalTo(reqBookingDto.getStart()));
вроде есть assertNotNull(), но пойдет

2023-06-25 14:21 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2023-06-26 13:13 UTC, merged