16 ТЗ Add docker
SergeiBrin/java-shareit pull request #4
Opened 2023-07-06 09:25 UTC by SergeiBrin

2023-07-06 18:48 UTC, SergeiBrin commented
Привет, Эркин. Как дела? Солнышко греет? :)

Блин, 16 ТЗ оказалось очень хитрым - конкретно при проверке на гитхаб.... Прикол тут в том, что по месту все работало без проблем, а вот на гитхаб - неееет. Я двое суток все перепроверял и переделывал по 10 раз - и все без толку... Так много работы и нервов - и все из-за одной строчки со временем. Слава богу, что мне один хороший парень подсказал про это. И вот я на ночь глядя сижу уставший, но очень счастливый. Сегодня буду спааааааать))))))

Жду  твоих оценочек :)

2023-07-07 10:51 UTC, ErkinKasymaliev requested changes
привет, все круто!
Оставил 1 коммент только

2023-07-07 10:51 UTC, ErkinKasymaliev commented on server/pom.xml
> +			<groupId>javax.validation</groupId>
эту зависимость удали

2023-07-07 21:42 UTC, SergeiBrin commented on server/pom.xml
> +			<groupId>javax.validation</groupId>
:white_check_mark:

2023-07-07 21:47 UTC, SergeiBrin commented on server/pom.xml
> +			<groupId>javax.validation</groupId>
Сделано :smiley:

2023-07-08 16:37 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-07-10 04:05 UTC, merged